apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-configmap
data:
  eureka.client.serviceUrl.defaultZone: "http://discovery-sts-0.discovery-service:8761/eureka,http://discovery-sts-1.discovery-service:8761/eureka,http://discovery-sts-2.discovery-service:8761/eureka"
  eureka.client.registerWithEureka: "true"
  eureka.client.fetchRegistry: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-sts
spec:
  serviceName: discovery-service
  replicas: 3
  selector:
    matchLabels:
      app: discovery-app
  template:
    metadata:
      labels:
        app: discovery-app
    spec:
      containers:
        - name: discovery-container
          envFrom:
            - configMapRef:
                name: discovery-configmap
          image: eureka-rnd/discovery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-app
spec:
  clusterIP: None
  selector:
    app: discovery-app
  ports:
    - port: 8761
