server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    id: ${random.value}
    name: dumb-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: info
