server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    id: ${random.value}
    name: demo-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 180

logging:
  level:
    root: debug
